export const REVERB_SECONDS = 2;
export const REVERB_DECAY = 2.4;
export const HUMANIZE = {
  detuneCents: 0.8,
  gainAmount: 0.1,
  attackSeconds: 0.008,
  decaySeconds: 0.03,
  cutoffAmount: 0.12,
  panAmount: 0.22,
  fxSendAmount: 0.12,
};
export const MAX_SIMULTANEOUS_PRESETS = 12;
export const DEFAULT_NOTE_IDS = ["note-c4", "note-e4", "note-g4"];
export const NOTE_OPTIONS = [
  { id: "note-c4", frequency: 261.63 },
  { id: "note-cs4", frequency: 277.18 },
  { id: "note-d4", frequency: 293.66 },
  { id: "note-ds4", frequency: 311.13 },
  { id: "note-e4", frequency: 329.63 },
  { id: "note-f4", frequency: 349.23 },
  { id: "note-fs4", frequency: 369.99 },
  { id: "note-g4", frequency: 392.0 },
  { id: "note-gs4", frequency: 415.3 },
  { id: "note-a4", frequency: 440.0 },
  { id: "note-as4", frequency: 466.16 },
  { id: "note-b4", frequency: 493.88 },
  { id: "note-c5", frequency: 523.25 },
  { id: "note-cs5", frequency: 554.37 },
  { id: "note-d5", frequency: 587.33 },
  { id: "note-ds5", frequency: 622.25 },
  { id: "note-e5", frequency: 659.25 },
  { id: "note-f5", frequency: 698.46 },
  { id: "note-fs5", frequency: 739.99 },
  { id: "note-g5", frequency: 783.99 },
  { id: "note-gs5", frequency: 830.61 },
  { id: "note-a5", frequency: 880.0 },
  { id: "note-as5", frequency: 932.33 },
  { id: "note-b5", frequency: 987.77 },
];
export const BASE_SOUND_PRESETS = {
  "warm-pad": {
    oscAWave: "sawtooth",
    oscBWave: "triangle",
    subWave: "sine",
    detuneSpread: 3,
    subLevel: 0.45,
    filterCutoff: 1700,
    filterQ: 1.2,
    attack: 0.12,
    decay: 0.55,
    release: 0.14,
  },
  pluck: {
    oscAWave: "square",
    oscBWave: "triangle",
    subWave: "sine",
    detuneSpread: 1.2,
    subLevel: 0.25,
    filterCutoff: 2500,
    filterQ: 2.2,
    attack: 0.01,
    decay: 0.18,
    release: 0.05,
  },
  organ: {
    oscAWave: "square",
    oscBWave: "sine",
    subWave: "triangle",
    detuneSpread: 0.6,
    subLevel: 0.35,
    filterCutoff: 3200,
    filterQ: 0.8,
    attack: 0.03,
    decay: 0.25,
    release: 0.1,
  },
  bass: {
    oscAWave: "sawtooth",
    oscBWave: "square",
    subWave: "sine",
    detuneSpread: 2,
    subLevel: 0.7,
    filterCutoff: 900,
    filterQ: 1.6,
    attack: 0.015,
    decay: 0.32,
    release: 0.08,
  },
  "glass-shimmer": {
    oscAWave: "triangle",
    oscBWave: "sine",
    subWave: "sine",
    detuneSpread: 6,
    subLevel: 0.18,
    filterCutoff: 4200,
    filterQ: 3.2,
    attack: 0.03,
    decay: 0.22,
    release: 0.18,
    stereoPan: 0.2,
    reverbSend: 0.45,
  },
  "acid-bite": {
    oscAWave: "sawtooth",
    oscBWave: "square",
    subWave: "triangle",
    detuneSpread: 1.5,
    subLevel: 0.2,
    filterCutoff: 1100,
    filterQ: 4.8,
    attack: 0.01,
    decay: 0.2,
    release: 0.06,
    delaySend: 0.08,
    reverbSend: 0.12,
    distortionDrive: 0.58,
    distortionMix: 0.38,
    distortionTone: 2600,
  },
  "hollow-drift": {
    oscAWave: "triangle",
    oscBWave: "triangle",
    subWave: "sine",
    detuneSpread: 8,
    subLevel: 0.3,
    filterCutoff: 1400,
    filterQ: 0.6,
    attack: 0.2,
    decay: 0.45,
    release: 0.24,
    stereoPan: -0.25,
    reverbSend: 0.4,
  },
  "noisy-spark": {
    oscAWave: "square",
    oscBWave: "square",
    subWave: "sine",
    detuneSpread: 12,
    subLevel: 0.1,
    filterCutoff: 3600,
    filterQ: 5.5,
    attack: 0.005,
    decay: 0.1,
    release: 0.03,
    delaySend: 0.16,
    delayFeedback: 0.38,
    stereoPan: 0.35,
    distortionDrive: 0.72,
    distortionMix: 0.52,
    distortionTone: 4200,
  },
  "deep-space": {
    oscAWave: "sine",
    oscBWave: "triangle",
    subWave: "sine",
    detuneSpread: 0.8,
    subLevel: 0.75,
    filterCutoff: 700,
    filterQ: 1.1,
    attack: 0.25,
    decay: 0.6,
    release: 0.3,
    delaySend: 0.32,
    delayTime: 0.4,
    reverbSend: 0.5,
    stereoPan: -0.1,
  },
  "rubber-seq": {
    oscAWave: "sawtooth",
    oscBWave: "triangle",
    subWave: "triangle",
    detuneSpread: 2.8,
    subLevel: 0.35,
    filterCutoff: 1500,
    filterQ: 2.8,
    attack: 0.02,
    decay: 0.16,
    release: 0.07,
    delaySend: 0.14,
    delayFeedback: 0.22,
  },
  "metal-cloud": {
    oscAWave: "square",
    oscBWave: "sawtooth",
    subWave: "sine",
    detuneSpread: 9,
    subLevel: 0.22,
    filterCutoff: 2800,
    filterQ: 3.8,
    attack: 0.04,
    decay: 0.38,
    release: 0.2,
    reverbSend: 0.42,
    stereoPan: 0.15,
    distortionDrive: 0.44,
    distortionMix: 0.3,
    distortionTone: 3200,
  },
  "pixel-tone": {
    oscAWave: "square",
    oscBWave: "square",
    subWave: "triangle",
    detuneSpread: 0.2,
    subLevel: 0.28,
    filterCutoff: 3000,
    filterQ: 1.5,
    attack: 0.005,
    decay: 0.08,
    release: 0.04,
    delaySend: 0.05,
    reverbSend: 0.06,
  },
  "wide-chorus": {
    oscAWave: "sawtooth",
    oscBWave: "sine",
    subWave: "triangle",
    detuneSpread: 10,
    subLevel: 0.25,
    filterCutoff: 2400,
    filterQ: 1.0,
    attack: 0.09,
    decay: 0.42,
    release: 0.18,
    delaySend: 0.2,
    reverbSend: 0.34,
    stereoPan: -0.2,
  },
  "sub-rumble": {
    oscAWave: "triangle",
    oscBWave: "sine",
    subWave: "sine",
    detuneSpread: 1.1,
    subLevel: 0.95,
    filterCutoff: 550,
    filterQ: 1.9,
    attack: 0.03,
    decay: 0.26,
    release: 0.11,
    delaySend: 0.07,
    reverbSend: 0.1,
    stereoPan: 0,
  },
};
export const DEFAULT_PRESET_ID = "warm-pad";
export const GLOBAL_CONTROL_KEYS = new Set([
  "tempoBpm",
  "masterVolume",
  "reverbMix",
  "delayTime",
  "delayFeedback",
]);

export const INITIAL_SYNTH_PARAMS = {
  tempoBpm: 120,
  attack: 0.1,
  decay: 0.5,
  release: 0.08,
  filterCutoff: 1600,
  filterQ: 1.1,
  detuneSpread: 3,
  subLevel: 0.45,
  stereoPan: 0,
  distortionDrive: 0.3,
  distortionMix: 0.2,
  distortionTone: 4500,
  delaySend: 0.35,
  delayTime: 0.24,
  delayFeedback: 0.26,
  reverbMix: 0.7,
  reverbSend: 0.24,
  masterVolume: 0.75,
  oscAWave: "sawtooth",
  oscBWave: "triangle",
  subWave: "sine",
};

export const controlConfig = {
  "tempo-bpm": {
    key: "tempoBpm",
    valueId: "tempo-bpm-value",
    formatter: (value) => String(Math.round(value)),
  },
  attack: {
    key: "attack",
    valueId: "attack-value",
    formatter: (value) => value.toFixed(2),
  },
  decay: {
    key: "decay",
    valueId: "decay-value",
    formatter: (value) => value.toFixed(2),
  },
  release: {
    key: "release",
    valueId: "release-value",
    formatter: (value) => value.toFixed(2),
  },
  "filter-cutoff": {
    key: "filterCutoff",
    valueId: "filter-cutoff-value",
    formatter: (value) => String(Math.round(value)),
  },
  "filter-q": {
    key: "filterQ",
    valueId: "filter-q-value",
    formatter: (value) => value.toFixed(2),
  },
  "detune-spread": {
    key: "detuneSpread",
    valueId: "detune-spread-value",
    formatter: (value) => value.toFixed(1),
  },
  "sub-level": {
    key: "subLevel",
    valueId: "sub-level-value",
    formatter: (value) => value.toFixed(2),
  },
  "stereo-pan": {
    key: "stereoPan",
    valueId: "stereo-pan-value",
    formatter: (value) => value.toFixed(2),
  },
  "distortion-drive": {
    key: "distortionDrive",
    valueId: "distortion-drive-value",
    formatter: (value) => value.toFixed(2),
  },
  "distortion-mix": {
    key: "distortionMix",
    valueId: "distortion-mix-value",
    formatter: (value) => value.toFixed(2),
  },
  "distortion-tone": {
    key: "distortionTone",
    valueId: "distortion-tone-value",
    formatter: (value) => String(Math.round(value)),
  },
  "delay-send": {
    key: "delaySend",
    valueId: "delay-send-value",
    formatter: (value) => value.toFixed(2),
  },
  "delay-time": {
    key: "delayTime",
    valueId: "delay-time-value",
    formatter: (value) => value.toFixed(2),
  },
  "delay-feedback": {
    key: "delayFeedback",
    valueId: "delay-feedback-value",
    formatter: (value) => value.toFixed(2),
  },
  "reverb-mix": {
    key: "reverbMix",
    valueId: "reverb-mix-value",
    formatter: (value) => value.toFixed(2),
  },
  "reverb-send": {
    key: "reverbSend",
    valueId: "reverb-send-value",
    formatter: (value) => value.toFixed(2),
  },
  "master-volume": {
    key: "masterVolume",
    valueId: "master-volume-value",
    formatter: (value) => value.toFixed(2),
  },
};

