import {
  DEFAULT_MIDI_CHANNEL_SETTINGS_BY_PRESET_ID,
  DEFAULT_GLOBAL_ARPEGGIO_KEY_INDEX,
  DEFAULT_PRESET_ID,
  INITIAL_SYNTH_PARAMS,
  MIXER_CHANNEL_IDS,
} from "./constants.js";
export const state = {
  synthParams: { ...INITIAL_SYNTH_PARAMS },
  audioContext: undefined,
  transportState: "stopped",
  schedulerId: null,
  schedulerChannel: null,
  nextNoteTime: 0,
  stepIndex: 0,
  masterGain: null,
  compressor: null,
  delayNode: null,
  delayFeedback: null,
  delayDrive: null,
  delayHighpass: null,
  delayReturnGain: null,
  delayTone: null,
  cleanDelayNode: null,
  cleanDelayFeedback: null,
  cleanDelayReturnGain: null,
  reverbConvolver: null,
  reverbInput: null,
  reverbWetGain: null,
  reverbDryGain: null,
  distortionFeedbackBusByPresetId: {},
  activeChannelLevelGainsByPresetId: {},
  activePresetIds: MIXER_CHANNEL_IDS.slice(),
  channelAssignedPresetIdById: Object.fromEntries(
    MIXER_CHANNEL_IDS.map((presetId) => [presetId, presetId]),
  ),
  instrumentParamsByPresetId: {},
  instrumentArpeggioPitchClassesByPresetId: {},
  instrumentArpeggioOctavesByPresetId: {},
  instrumentNoteIdsByPresetId: {},
  instrumentNoteLengthInitializedByPresetId: {},
  instrumentPatternsByPresetId: {},
  instrumentPatternNoteIdsByPresetId: {},
  globalArpeggioKeyIndex: DEFAULT_GLOBAL_ARPEGGIO_KEY_INDEX,
  startupRandomizationApplied: false,
  currentStateSeed: "",
  arpeggioHistorySnapshots: [],
  arpeggioHistoryIndex: 0,
  activeInstrumentPresetId: DEFAULT_PRESET_ID,
  playingPresetIds: new Set(),
  midi: {
    supported: false,
    accessGranted: false,
    crossTabSyncSupported: false,
    crossTabSyncActive: false,
    tabId: "",
    inputPortId: "",
    outputPortId: "",
    availableInputs: [],
    availableOutputs: [],
    clockMode: "off",
    clockMasterRunning: false,
    awaitingExternalClockStart: false,
    externalClockPulseCount: 0,
    externalClockTempoBpm: 0,
    lastExternalClockTimestampMs: 0,
    channelSettingsByPresetId: Object.fromEntries(
      Object.entries(DEFAULT_MIDI_CHANNEL_SETTINGS_BY_PRESET_ID).map(([presetId, value]) => [presetId, { ...value }]),
    ),
  },
};
