import {
  DEFAULT_GLOBAL_ARPEGGIO_KEY_INDEX,
  DEFAULT_PRESET_ID,
  INITIAL_SYNTH_PARAMS,
  MIXER_CHANNEL_IDS,
} from "./constants.js";
export const state = {
  synthParams: { ...INITIAL_SYNTH_PARAMS },
  audioContext: undefined,
  schedulerId: null,
  schedulerChannel: null,
  nextNoteTime: 0,
  stepIndex: 0,
  masterGain: null,
  compressor: null,
  delayNode: null,
  delayFeedback: null,
  delayDrive: null,
  delayHighpass: null,
  delayReturnGain: null,
  delayTone: null,
  cleanDelayNode: null,
  cleanDelayFeedback: null,
  cleanDelayReturnGain: null,
  reverbConvolver: null,
  reverbInput: null,
  reverbWetGain: null,
  reverbDryGain: null,
  distortionFeedbackBusByPresetId: {},
  activePresetIds: MIXER_CHANNEL_IDS.slice(),
  channelAssignedPresetIdById: Object.fromEntries(
    MIXER_CHANNEL_IDS.map((presetId) => [presetId, presetId]),
  ),
  instrumentParamsByPresetId: {},
  instrumentArpeggioPitchClassesByPresetId: {},
  instrumentArpeggioOctavesByPresetId: {},
  instrumentNoteIdsByPresetId: {},
  instrumentNoteLengthInitializedByPresetId: {},
  instrumentPatternsByPresetId: {},
  globalArpeggioKeyIndex: DEFAULT_GLOBAL_ARPEGGIO_KEY_INDEX,
  activeInstrumentPresetId: DEFAULT_PRESET_ID,
  playingPresetIds: new Set(),
};
