export const MAX_SIMULTANEOUS_PRESETS = 8;

export const MIDI_CHANNEL_MIN = 1;
export const MIDI_CHANNEL_MAX = 16;
export const MIDI_VELOCITY_MIN = 0;
export const MIDI_VELOCITY_MAX = 127;

export const DEAD_NOTE_PAUSE_COUNT_MIN = 1;
export const DEAD_NOTE_PAUSE_COUNT_MAX = 16;

export const DELAY_FEEDBACK_MAX = 1;
export const STARTUP_DELAY_FEEDBACK_MAX = 0.05;
export const DELAY_FEEDBACK_LOG_MIN = 0.001;
export const TAPE_DELAY_SEND_MAX = 0.1;
export const CLEAN_DELAY_REPETITIONS_MIN = 1;
export const CLEAN_DELAY_REPETITIONS_MAX = 12;
export const CLEAN_DELAY_REPEAT_GAIN_CAP = 0.92;

export const DISTORTION_FEEDBACK_MAX = 0.35;
export const DISTORTION_FEEDBACK_DELAY_MIN_SECONDS = 0.075;
export const DISTORTION_FEEDBACK_DELAY_MAX_SECONDS = 0.22;
export const DISTORTION_FEEDBACK_SEND_MAX = 0.24;
export const DISTORTION_FEEDBACK_LOOP_MAX = 0.29;
export const DISTORTION_FEEDBACK_RETURN_MAX = 0.2;

export const PITCH_SHIFT_MIN_SEMITONES = -24;
export const PITCH_SHIFT_MAX_SEMITONES = 24;
export const LFO_PITCH_SHIFT_MAX_SEMITONES = 4;

export const LFO_RATE_MIN_HZ = 0.05;
export const LFO_RATE_MAX_HZ = 12;

export const ENVELOPE_ATTACK_MIN_SECONDS   = 0.001;
export const ENVELOPE_ATTACK_MAX_SECONDS = 2;
export const ENVELOPE_DECAY_MIN_SECONDS = 0.005;
export const ENVELOPE_DECAY_MAX_SECONDS = 2;
export const ENVELOPE_RELEASE_MIN_SECONDS = 0.01;
export const ENVELOPE_RELEASE_MAX_SECONDS = 2;

